
//auth actions
export const AUTH_START = 'AUTH_START' ;
export const AUTH_FAIL = 'AUTH_FAIL' ;
export const AUTH_SUCCESS = 'AUTH_SUCCESS' ;
export const AUTH_LOGOUT = 'AUTH_LOGOUT' ;

// export const FACEBOOK_AUTH_START='FACBOOK_LOGIN_START'
// export const FACEBOOK_AUTH_FAIL='FACBOOK_LOGIN_FAIL'
// export const FACEBOOK_AUTHH_SUCCESS='FACBOOK_LOGIN_SUCCESS'
// export const FACEBOOK_LOGOUT='FACBOOK_LOGOUT'

// export const GOOGLE_AUTH_START=' GOOGLE_LOGIN_START'
// export const  GOOGLE_AUTH_FAIL=' GOOGLE_LOGIN_FAIL'
// export const  GOOGLE_AUTHH_SUCCESS=' GOOGLE_LOGIN_SUCCESS'
// export const  GOOGLE_LOGOUT=' GOOGLE_LOGOUT'





//blogactions



export const GET_USER_BLOGS='GET_USER_BLOGS' ;
export const GOT_USER_BLOGS='GOT_USER_BLOGS' ;
export const CANT_GET_USER_BLOGS='CANT-GET_USER_BLOGS' ;

export const GET_FOLLOWED_BLOGS='GET_USER_FOLLOWED_BLOGS' ;
export const GOT_FOLLOWED_BLOGS='GOT_USER_FOLLOWED_BLOGS' ;
export const CANT_GET_FOLLOWED_BLOGS='CANT_GET_USER_FOLLOWED_BLOGS' ;


export const GET_TOP_BLOGS='GET_TOP_BLOGS' ;
export const GOT_TOP_BLOGS='GOT_TOP_BLOGS' ;
export const CANT_GET_TOP_BLOGS='CANT_GET_TOP_BLOGS' ;
export const CREATE_BLOG_START = 'CREATE_BLOG_START'
export const BLOG_CREATED = 'BLOG_CREATED'
export const BLOG_CREATE_FAILED = 'BLOG_CREATE_FAILED'


export const BLOGS_GET='BLOGS_GET' ;
export const BLOGS_GOT='BLOGS_GOT' ;
export const BLOGS_GET_FAIL='BLOGS_GET_FAIL' ;





//articles

export const GET_USER_ARTICLES='GET_USER_ARTICLES' ;
export const GOT_USER_ARTICLES='GOT_USER_ARTICLES' ;
export const CANT_GET_USER_ARTICLES='CANT_GET_USER_ARTICLES' ;


export const GET_RECOMMENDED_ARTICLES='GET_USER_RECOMMENDED_ARTICLES' ;
export const GOT_RECOMMENDED_ARTICLES='GOT_USER_RECOMMENDED_ARTICLES' ;
export const CANT_RECOMMENDED_ARTICLES='CANT_GET_USER_RECOMMENDED_ARTICLES' ;


export const GET_TOP_ARTICLES='GET_TOP_ARTICLES' ;
export const GOT_TOP_ARTICLES='GOT_TOP_ARTICLES' ;
export const CANT_GET_TOP_ARTICLES='CANT_GET_TOP_ARTICLES' ;

export const ARTICLES_GET='ARTICLES_GET' ;
export const ARTICLES_GOT='ARTICLES_GOT' ;
export const ARTICLES_GET_FAIL='ARTICLES_GET_FAIL' ;





//COMMENTS AND REPLIES AND NOTIFICATIONS

export const ADD_RESPONSE='ADD_RESPONSE' ;
export const SET_RESPONSE='SET_RESPONSE' ;



